export const AuthTypes = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',

	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export const AddUserType = {
	ADD_USER_REQUEST: 'ADD_USER_REQUEST',
	ADD_USER_FAILURE: 'ADD_USER_FAILURE',
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
};

export const CategoryType = {
	GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
	GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
	GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
	ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
	ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE',
	ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
};
